# Volatility Model Fitting Configuration
# Configuration file for volatility surface modeling and calibration

# Data Configuration
data:
  # Date string in YYYYMMDD format for market data
  date_str: "20240229"
  
  # Data source configuration
  use_orderbook_data: true
  orderbook_level: 0
  
# Market data processing
market_data:
  # Minimum number of strikes required for calibration
  min_strikes: 5
  
  # Strike range constraints (as percentage of forward price)
  min_strike_ratio: 0.7  # 70% of forward price
  max_strike_ratio: 1.3  # 130% of forward price
  
  # Minimum time to expiry (in years) for analysis
  min_time_to_expiry: 0.01  # ~4 days
  
  # Volatility data validation
  min_volatility: 0.05   # 5% minimum volatility
  max_volatility: 5.0    # 500% maximum volatility

# Analysis Configuration
analysis:

# Fitting Algorithm Parameters
fitting:


# Result Management
results:

# Model Configuration
models:
  # Model execution toggles
  enabled_models:
    wing_model: false              # Enable/disable Traditional Wing Model
    time_adjusted_wing_model: true # Enable/disable Time-Adjusted Wing Model
  
  # Wing Model settings
  wing_model:
    
    # Parameter bounds for calibration
    bounds:
      vr: [0.05, 5.0]      # volatility reference bounds
      sr: [-2.0, 2.0]      # slope reference bounds  
      pc: [-5.0, 5.0]      # put curvature bounds
      cc: [-5.0, 5.0]      # call curvature bounds
      dc: [-2.0, 0.0]      # down cutoff bounds (must be negative)
      uc: [0.0, 2.0]       # up cutoff bounds (must be positive)
      dsm: [0.01, 2.0]     # down smoothing bounds (must be positive)
      usm: [0.01, 2.0]     # up smoothing bounds (must be positive)
  
  # Time-Adjusted Wing Model settings (uses same parameters as wing_model)
  time_adjusted_wing_model:
    # Use normalization term
    use_norm_term: true
        
    # Same bounds as wing_model
    bounds:
      vr: [0.05, 5.0]
      sr: [-2.0, 2.0]
      pc: [-5.0, 5.0]
      cc: [-5.0, 5.0]
      dc: [-2.0, 0.0]
      uc: [0.0, 2.0]
      dsm: [0.01, 2.0]
      usm: [0.01, 2.0]

# Calibration Configuration
calibration:
  # Unified calibrator settings
  unified_calibrator:
    # Optimization settings
    enable_bounds: true
    tolerance: 1e-10
    method: "SLSQP"  # Options: SLSQP, L-BFGS-B, Powell
    max_iterations: 1000
    arbitrage_penalty: 1e5
    
    # Multi-start optimization
    multi_start:
      enabled: false
      num_starts: 5
      random_seed: 42
  
  # Model-specific settings
  model_specific:
    # Whether to enforce arbitrage-free constraints
    enforce_arbitrage_free: true
    
    # Additional constraints
    additional_constraints: []
  
  # Weighting scheme for calibration
  weighting:
    # How to weight strikes in calibration
    # Options: "equal", "vega", "volume", "bid_ask_spread"
    scheme: "vega"
    
    # Vega weighting settings (if scheme is "vega")
    vega:
      # Minimum vega threshold
      min_vega: 0.01
      # Normalize vega weights
      normalize: true

# Validation and Quality Control
validation:
  # Arbitrage checking
  arbitrage:
    # Durrleman condition settings
    durrleman:
      # Number of points for Durrleman condition check
      num_points: 501
      # Minimum g-value threshold (should be positive)
      min_g_value: 0.0
    
    # Strike range bounds for arbitrage checking
    arbitrage_bounds:
      lower_bound: 0.5  # 50% of forward price
      upper_bound: 2.0  # 200% of forward price
  
  # Calibration quality metrics
  quality:
    # Maximum acceptable RMSE
    max_rmse: 0.1  # 10% RMSE threshold
    
    # Minimum R-squared for goodness of fit
    min_r_squared: 0.8
    
    # Maximum parameter change tolerance between iterations
    max_param_change: 1e-6

# Output and Reporting
output:
  # Volatility surface generation
  surface:
    # Number of strikes for surface generation
    num_strikes: 100
    
    # Strike range for surface (as ratio of forward price)
    strike_range: [0.5, 2.0]
    
    # Output precision (decimal places)
    precision: 6
  
  # Plotting and visualization
  plotting:
    # Default plot settings
    show_bid_ask_spread: true
    show_market_data: true
    show_fitted_curve: true
    show_error_bars: true
    
    # Plot styling
    theme: "plotly_white"
    width: 800
    height: 600
    
    # Error bar settings
    error_bars:
      # Show bid/ask spread as error bars
      show_spread: true
      # Error bar transparency
      opacity: 0.3
  
  # Export settings
  export:
    # File formats to export
    formats: ["csv", "json"]
    
    # Export directory
    export_dir: "volatility_results"
    
    # Include metadata in export
    include_metadata: true

# Performance and Debugging
performance:
  # Parallel processing
  parallel:
    # Enable parallel processing where applicable
    enabled: false
    # Number of processes (-1 for auto)
    num_processes: -1
  
  # Caching
  cache:
    # Cache calibration results
    enabled: false
    # Cache directory
    cache_dir: ".volatility_cache"
  
  # Debugging
  debug:
    # Enable debug mode
    enabled: false
    # Verbose output
    verbose: false
    # Save intermediate results
    save_intermediate: false

# Paths and File Management
paths:
  # Data directories (relative to project root)
  data_bbo: "data_bbo"
  data_orderbook: "data_orderbook"
  
  # Output directories
  results: "volatility_results"
  plots: "volatility_plots"
  exports: "volatility_exports"
  
  # Notebook directory
  notebooks: "notebooks"
  
  # Default data file patterns
  data_file_pattern_bbo: "{data_dir}/{date_str}.market_updates.log"
  data_file_pattern_orderbook: "{data_dir}/{date_str}.output.csv.gz"

# Development and Testing
development:
  # Test mode settings
  test_mode:
    # Use synthetic data for testing
    use_synthetic_data: false
    
    # Reduced dataset for quick testing
    quick_test: false
    
    # Test data parameters
    synthetic_data:
      num_strikes: 20
      forward_price: 60000.0
      time_to_expiry: 0.25
      atm_vol: 0.7
      
  # Regression testing
  regression:
    # Save results for regression testing
    save_baselines: false
    # Baseline directory
    baseline_dir: "test_baselines"
    # Tolerance for regression tests
    tolerance: 1e-6